apiVersion: v1
kind: ServiceAccount
metadata:
  name: stock
  namespace: oms
  labels:
    app: stock
    component: backend-service
    app.kubernetes.io/name: stock
    app.kubernetes.io/part-of: oms
automountServiceAccountToken: true
