apiVersion: v1
kind: ConfigMap
metadata:
  name: oms-config
  namespace: oms
data:
  MONGO_URI: "mongodb://mongodb.oms.svc.cluster.local:27017/orders"
  POSTGRES_HOST: "postgres.oms.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "stock"
  POSTGRES_DB: "stock"
  POSTGRES_PASSWORD: "stock123"
  POSTGRES_URI: "postgresql://stock:stock123@postgres.oms.svc.cluster.local:5432/stock?sslmode=disable"
  AMQP_USER: "guest"
  AMQP_PASS: "guest"
  AMQP_HOST: "rabbitmq.oms.svc.cluster.local"
  AMQP_PORT: "5672"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASS: "guest"
  RABBITMQ_HOST: "rabbitmq.oms.svc.cluster.local"
  RABBITMQ_PORT: "5672"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq.oms.svc.cluster.local:5672/"
  REDIS_ADDR: "redis.oms.svc.cluster.local:6379"
  ORDERS_GRPC_ADDR: "orders.oms.svc.cluster.local:9000"
  STOCK_GRPC_ADDR: "stock.oms.svc.cluster.local:9003"
  OTEL_EXPORTER_OTLP_ENDPOINT: ""
  STRIPE_KEY: "STRIPE_DEV_KEY_PLACEHOLDER"
  STRIPE_WEBHOOK_SECRET: "STRIPE_DEV_WEBHOOK_SECRET_PLACEHOLDER"
