---
# Redis Standalone for OMS
# Enterprise Best Practice: Standalone is faster and more resilient than Cluster
# for workloads that fit in single-node RAM (OMS caching use case)
# Reference: https://cloud.google.com/kubernetes-engine/docs/tutorials/upgrading-stateful-workload
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: oms
  labels:
    app: redis
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: oms
    app.kubernetes.io/component: database
    platform.homelab/tenant: oms
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        app.kubernetes.io/name: redis
        app.kubernetes.io/part-of: oms
        platform.homelab/tenant: oms
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          command:
            - redis-server
          args:
            - --appendonly
            - "yes"
            - --appendfsync
            - everysec
            - --maxmemory
            - "256mb"
            - --maxmemory-policy
            - allkeys-lru
            - --tcp-keepalive
            - "300"
            - --timeout
            - "0"
          ports:
            - containerPort: 6379
              name: redis
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 300Mi
          volumeMounts:
            - name: redis-data
              mountPath: /data
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
  volumeClaimTemplates:
    - metadata:
        name: redis-data
        labels:
          app: redis
          platform.homelab/tenant: oms
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: rook-ceph-block-enterprise
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: oms
  labels:
    app: redis
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: oms
    app.kubernetes.io/component: database
    platform.homelab/tenant: oms
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  selector:
    app: redis
