apiVersion: v1
kind: ConfigMap
metadata:
  name: oms-config
  namespace: oms
data:
  CONSUL_ADDR: "consul.oms.svc.cluster.local:8500"
  MONGO_URI: "mongodb://mongodb.oms.svc.cluster.local:27017/orders"
  AMQP_USER: "guest"
  AMQP_PASS: "guest"
  AMQP_HOST: "rabbitmq.oms.svc.cluster.local"
  AMQP_PORT: "5672"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASS: "guest"
  RABBITMQ_HOST: "rabbitmq.oms.svc.cluster.local"
  RABBITMQ_PORT: "5672"
  POSTGRES_HOST: "postgres.oms.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "stock"
  POSTGRES_PASSWORD: "stock123"
  POSTGRES_DB: "stock"
  REDIS_ADDR: "redis.oms.svc.cluster.local:6379"
  OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector.oms.svc.cluster.local:4317"
  ORDERS_GRPC_ADDR: "orders.oms.svc.cluster.local:9000"
  STOCK_GRPC_ADDR: "stock.oms.svc.cluster.local:9003"
