# Platform-provided Secrets for OMS Infrastructure
# Contains credentials (stringData for learning visibility)
#
# ============================================================================
# DYNAMIC SECRETS - PRODUCTION APPROACH
# ============================================================================
# In production, deployments should use secretKeyRef to reference operator-created secrets:
#
# MongoDB (Percona Operator creates: internal-mongodb-oms-users):
#   env:
#     - name: MONGO_USER
#       valueFrom:
#         secretKeyRef:
#           name: internal-mongodb-oms-users
#           key: MONGODB_DATABASE_ADMIN_USER
#     - name: MONGO_PASSWORD
#       valueFrom:
#         secretKeyRef:
#           name: internal-mongodb-oms-users
#           key: MONGODB_DATABASE_ADMIN_PASSWORD
#
# RabbitMQ (Operator creates: rabbitmq-default-user):
#   env:
#     - name: RABBITMQ_USER
#       valueFrom:
#         secretKeyRef:
#           name: rabbitmq-default-user
#           key: username
#     - name: RABBITMQ_PASSWORD
#       valueFrom:
#         secretKeyRef:
#           name: rabbitmq-default-user
#           key: password
#
# PostgreSQL (CNPG creates: <cluster>-app):
#   env:
#     - name: POSTGRES_USER
#       valueFrom:
#         secretKeyRef:
#           name: postgres-app
#           key: username
#     - name: POSTGRES_PASSWORD
#       valueFrom:
#         secretKeyRef:
#           name: postgres-app
#           key: password
# ============================================================================

apiVersion: v1
kind: Secret
metadata:
  name: oms-infra-secrets
  namespace: oms
  labels:
    app.kubernetes.io/name: oms-infra-secrets
    app.kubernetes.io/part-of: oms
    platform.homelab/managed-by: platform-team
type: Opaque
stringData:
  # ===========================================
  # MONGODB CREDENTIALS
  # ===========================================
  # Source: internal-mongodb-oms-users (Percona Operator)
  # User: databaseAdmin (has full DB management rights)
  MONGO_USER: "databaseAdmin"
  MONGO_PASSWORD: "databaseAdmin123456"

  # Full MongoDB URI (with credentials embedded for learning)
  # Format: mongodb://user:pass@host1,host2,host3/db?replicaSet=rs0&authSource=admin
  MONGO_URI: "mongodb://databaseAdmin:databaseAdmin123456@mongodb-oms-rs0-0.mongodb-oms-rs0.oms.svc.cluster.local:27017,mongodb-oms-rs0-1.mongodb-oms-rs0.oms.svc.cluster.local:27017,mongodb-oms-rs0-2.mongodb-oms-rs0.oms.svc.cluster.local:27017/orders?replicaSet=rs0&authSource=admin"

  # ===========================================
  # POSTGRESQL CREDENTIALS
  # ===========================================
  # Source: postgres-app (CloudNative PG) or static for StatefulSet
  POSTGRES_USER: "stock"
  POSTGRES_PASSWORD: "stock123"

  # Full PostgreSQL URI
  POSTGRES_URI: "postgresql://stock:stock123@postgres.oms.svc.cluster.local:5432/stock?sslmode=disable"

  # ===========================================
  # RABBITMQ CREDENTIALS
  # ===========================================
  # Source: rabbitmq-default-user (RabbitMQ Cluster Operator)
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "guest"
  AMQP_USER: "guest"
  AMQP_PASS: "guest"

  # Full RabbitMQ URL
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq.oms.svc.cluster.local:5672/"

  # ===========================================
  # REDIS (No Auth)
  # ===========================================
  REDIS_PASSWORD: ""
