apiVersion: v1
kind: ServiceAccount
metadata:
  name: customer-app
  namespace: oms
  labels:
    app: customer-app
    component: frontend
    app.kubernetes.io/name: customer-app
    app.kubernetes.io/part-of: oms
automountServiceAccountToken: false  # Frontend doesn't need K8s API access
