---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gateway-pdb
  namespace: oms
  labels:
    app: gateway
    component: api-gateway
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: oms
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: orders-pdb
  namespace: oms
  labels:
    app: orders
    component: backend-service
    app.kubernetes.io/name: orders
    app.kubernetes.io/part-of: oms
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: orders
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: payments-pdb
  namespace: oms
  labels:
    app: payments
    component: backend-service
    app.kubernetes.io/name: payments
    app.kubernetes.io/part-of: oms
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: payments
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: stock-pdb
  namespace: oms
  labels:
    app: stock
    component: backend-service
    app.kubernetes.io/name: stock
    app.kubernetes.io/part-of: oms
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: stock
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: customer-app-pdb
  namespace: oms
  labels:
    app: customer-app
    component: frontend
    app.kubernetes.io/name: customer-app
    app.kubernetes.io/part-of: oms
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: customer-app
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kitchen-display-pdb
  namespace: oms
  labels:
    app: kitchen-display
    component: frontend
    app.kubernetes.io/name: kitchen-display
    app.kubernetes.io/part-of: oms
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: kitchen-display
