---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stripe-secrets
  namespace: oms
  labels:
    app.kubernetes.io/name: stripe-secrets
    app.kubernetes.io/part-of: oms
    app.kubernetes.io/managed-by: sealed-secrets
spec:
  encryptedData:
    STRIPE_ENDPOINT_SECRET: AgB9lA9x7t6dfdOXePNFKON9/jiSjz4MpjOK1Mqu9vEKBeMUBNV4JcBsKW6HfMZTEh6zyNB82JD1YrKHDgFbuTM23d6ymYrBbFPE8RFuOlyJ4xFcLXfPUVoNJ9cmMWxZBcJ0srY2TOb3nVqOlruJmGt7o435cCIvJ8s9tOWKiCqCNdXUIaQCyCpEmi+L76nyirAcKxr2UsGkVVLKOC9uHtrKFOpV0N+uD5J/piouIheKnGYg5ksNySkC5wC2Y1gJUmjtNLHlbBOlx95oqFh9Ewe0kKhHEAqKrad/g8h7DyM/tfm03pnkHSJikX/gsvA4bR44vJo3nnGdZEsoYZV48Y78jG/9ZGv9O9Tw3LUH6OkmI5yWAoOEoBVM+7XOUxoAl88si1dtdRvG7M9wHpFttCM9I2gTOAhcCtFUk0gWshGfJXVQgDgqVCweeILZb+CYRljwJk/N8Kd1p7H8q5Kmwy/Pxp7oJUoB2UPS0eRRnIQblcixwq67InSh695BhtMAnl/xBRbZe1QMvZfOJn6cBJhEmmeXUgCcvDKbnq79zM/88Mu0De4uoDTbUtj09xu76ule2+yYyHbJQI970Ypi2Z9sW1myQE9ulXf/5vbkBaa1GGeBtL0lmDWyjZW1YqLcXOP50YkHTJzXJ81+pAhRS0TpZc022pAMmSVrO0IdCGA0fccyhT2FF8Yb3VlIZ9S3LAhDiv83OU1gKRmn36pvTjlfmB/GEPi8OAWx7Ty+BEBeCKVI4rOqy8FTec1JF3PY2psmw1dbqOlYVk3Qx0s7q4C0p01PhLus
    STRIPE_SECRET_KEY: AgA+O59HrHUWtAKtg700yf/frlEKamu1pWT63+3/JYutO3/qWtguEYc4Tlwdoo8YSsxPmVREd7S8bOH97unZQK2keyLlTeCjchrKSfg3pSwAE1pvwV1k9+ETUAIURiCWqEdXZzBCVnmkN0ler/ULL1je5XJ0WJEjgR4x2Zv4KoGW8UzybGy8E9RqQ8wH4ds6crTFMsWUPWEgd0m2LndcqY53MyEJkaaK3fg1zEjpj/GwcEincwHDo6E+mlQSyeGfrjEqVRWWB47ztm5U4LPsYJ0652orvDUJx62T40DELlvIaLiJgJVANso4BurlAVhf4ZSDkdR6uDnSHk33Y3vndwUg6Knf+hqBcvQBws07l1Lz49nmW5bk1vhrwlbYnDIHJTrxiL2yjDEhENZ1TAuX2O1Vd3W3DuiZPEzA+2wKtfgVAj9RzCatJr6qza+KFQ2ylmP5PCofF9duMa5pbjGeLgujXXX6JqzzG8+z4EdWG5cSAk6YnLhDAuuMBcES78WyyG7AKZ8fvvTORWu9IKp1s2GbfJ3ANRzUTfubx3lG2dJYJ6cv14faUNBwiJsoK7LlnTdHMDyGPV+SdP6RbwHb7zOuUvw2BEAIOiZtYfzHa3xnfOVl/NBZfBOjvW4bfZ2SMBO10SXQkemI5y7CczrP3NBAhWHdKKMRO0WmxjVWP8eBGmYzpreF6WNBsOt9IpP24pF3GTRPfZQbGq9d4GnlNolAW3A8imoJoMWabOrSRaCmWvjlenY4HCxGpJ+dW4VJUccS46HexwDMqsy+j7adMwFT8C5hY67Choo71XWD5LleMBZP6I9cABnhYWEL5/1hos50uoQwGuEc+U6SeA==
  template:
    metadata:
      name: stripe-secrets
      namespace: oms
      labels:
        app.kubernetes.io/name: stripe-secrets
        app.kubernetes.io/part-of: oms
    type: Opaque
