---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stripe-secrets
  namespace: oms
spec:
  encryptedData:
    STRIPE_ENDPOINT_SECRET: AgAzW1qd5w91orj7a+HCoN120TqdjI4GfB3mJQrKfqnBfaQsGqScSlOn9riOFsAtF4ndP3JFbg7ZGLhJ9q7O57mVnMOTxWmz+yL7Ls8y4PEjm4PppUqMg+D6ypVCC5C0TuS6lZZM7EFNWevOofpB2Nv03o6blcZDdyLutdf8vD/6j2PG+njsDHJSoT82nMDgkIehU7h07Wmh6nnI6njLazxaTB62dSY6DfhwAQTn4IIj2moHljzjkqqGlwNotDbfWUEQxZBcK2+zmVxOQjfTRCzo3PiANgB10gWMuMiM7rSMz+6OFsJiezJZ85CH4/0NWMjMPXIiRkN+BoRteghlpvrM5zqt5dJxUzlzC0PRXUQcMH2p/t2Xvr3zZHwbzp6beFa9oCGaCC0tOv44oc8vWlHDY18qkSM//IwzhunO0Y1SHH4KgTjf1bnPwdRGeDfatIUHXrvKYNFT5xla0j/0xbsKjkCMjSUoVLTJtK9gbe65zw4r1SdVjro5prnI+fJG4iwY3ozz1UulOAsMWnpY6kz9NCTI0u5NmjHq18SJSFIePLEinO2yib8/kFwDEwwW18A3aLhomlrxAy4YXv0iGq0PsNEiAO1Q0fSYLepVXj25560isujbILrttu6hQ/1izxbzbROkJYyudnePGgIWAQ03v9t2K/DU524Y3VCBxH4saVCPdPjLjrNv1ywtLxsnzY1oCcccDh1iFDqiewNNOqu6SexS0XlMM540KAqGHD1oClmt5YjZvQ==
    STRIPE_SECRET_KEY: AgCR9A6m8MkZqM3N4YAmMLWzerKtNdYsOauZNlwJx/SNw4xhjr4e6oL5JFJRqtRob4nI6pxR1qUz0AHUlQRwroDX8Ea/Iu9VcEzH/SSJHiLfgsKSzZOA8+eOLrDl4PbH6MmKqOYe0PxQG2DfSNp6bH2dQwEkZsLCyESWlgKCUgpl+knmmWe2Bmf2Htw+rHuIU5YMGaBsKR5Ry/Py2GFOdmuYUCoLUcFKZT8cJ3CRYhBe2ZtVgrs+v8pHkbWumtpwOWIVD1zB2tO4DlvG+f6A/7f1NmEZPO9Jj3kK6jAOchuHKhYm/42AiJ5euhUTzBcjzHXt3uYa4z0nbcNXQzNw02Ob0iyQA61ozUF5c+bR/eINxAkuBHi3aHmkD4jvAaFJWhz7VIDo7BbY64w+dInR3I98jYNdzdvln6zTOE0Zr7um8e3HseweTk7SlpxHcB6iH61sgwc5Euoizir/N9MZOTGkolDUyALb0agq1Z0JSPHgEfKy47xU0FHq7RjNr/piX1TU9kuSw2ktAnhYkMLy8HlET/gkMh1dt+PXESHv3HLnyO/FZwu26YIgmKlZw+yl7oh1De5Kaint2s74TNlpYvofj6DeYQyLiYtO0GZD6dxpE9mxsALcfY6LFXxDZ3qWUPhbdC19HR8FPHVYN5kdhfE3LB3VdTYsmGzd7VIXNMHfeEHSypsc87hspIg6oAZ+0X6mLjFLw8qecEDSiuSgcJv3TSKeKlWv4/5Bnb8LMmGnFq77wURk7Jdb48Xxs/NREpCKTX1w/dMyMlLdazC3fMJFUCNc1bx0Ah3FnOGW7Pytm5kQ2DHg3N9BAX0x4o7cmW1xl/NZDkwr93vN8w==
  template:
    metadata:
      name: stripe-secrets
      namespace: oms
    type: Opaque
