---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stripe-secrets
  namespace: oms
spec:
  encryptedData:
    STRIPE_ENDPOINT_SECRET: AgBfuXqjQaM5VQ6PLLO576T2nqhwqmTqRnr5qKSV+aTEvmk1U05syUJVLF4JEkiCWxdw5jTI18jESVa23rq8F4G01rpEUt6MG1cqH+pOx3F1Twl599F6efOr7GS8YYVwFskXPspWhXt4wAcUcx+byyBHjlVk2Vto7OTqN1vJkPmUGyG2Cq2CCXUaVw2GjwmH6VpXx2W41euvP9Z55qbKUk54Rf9wFbt3gPgx1RRl8SF9kbxohEtO7YQ3KdiX/VktTiAfA5mJ6ha0F/gKslRfkWxn5kQAKmLGVQlQjs5GAzm1nmIz7oXFd/1xHO126Uw7n94Vqn42YgQhBjg903jk1sV0KY3EhgNFJhXuMdmqzEEsrxR6G7xSxrpk6stKP1L5G9L/+1pq/y/bpRQGP/VJAzZGvK94kCCVMf8AncnWbaq4MRSrel1jVox+JIhtPWDDYZb7AWZVyvyC28gIu2Cp8iIq8b356Y5FBPmtMs/RLqwLAz9AIpU+UDslVKlsOXCWA3FYoOlMHuSa9qW8Wm8i3AL2S/E5cusqLwTioe12mc/qicSf9FqxvHOcdLvlcgNARuAklSrS5wLyESPLteverPjEpCxpQGYKHPi+tg2tLBd2WkgLLYDngyIpQD6ApRd1hT0gwjidIXTt0msNNw2MFlxCuLQbw69u6BF2/mKbmAC11EXjJa8LyR2V5VzhT4zM2/Vqt0DFqqNiZ2HxIn6Kh016UeqzY8XkkKByOjZtpjEXZLhLh6okGQ==
    STRIPE_SECRET_KEY: AgBKnPKUuwML9TIrDpuyn8QzuSkOlwp61mm6xY5xOllDNSeWt3BvqRHBrjBNNUwjjzIFZu+hZKZDw9s9bb5xaZoYg1/htsW0W/1FTMzqzCP4LqQkos87fZ0xA1eDGSp1tHzI5c0hONm9oRSQjyHH6MEm2eDB9dwyFKa+ojydBQ4I70xZ6pQBO3X3a/PDva6PVGG7VCtygpBLHd34P01Qp0lG6DScSlm7zzOrUtANHnb98uwc8R9Z5B1KmBKY0H0Uj4emDXV1INfoZebsCyFuVc7KIK9LdYE5RcmxWUsGRNmoFtRDsYbz1zrtv6BdwWrvljauCNkwo4PYNad5utCJIgvmwex0KgZE0+ibR0QoNUqQlyicYGhVj9qkkzBS7elHwSoB2BnnzgvVYklNf+mSYqsnU96BQe5AXStsgUGVZsIaC6YewexGCU0eQnYhhvRaxt4K4Ro41GyQVr2YeMPlTxpyv/SGdDceeTPCZHAfBvgT37F9Ps6rWB5/DrdRoW76W//VW4XscU2UIn2tfrRO+V8t30ZsHRjo9zEYpBDKhltkJiW2VjFcNIGpftAfUs34JJN/rEVdIyVbaBLcJsEkbx0ix21voZoRQq3sm8kPFgYbn9FWoigDKT9Aht0DmyxqX28uwwfrBn431rvEGeihvIum1K6xVD9w4VdznqA2G+SP97P8NSatQs7gvmA9EHWx1VOijnK5v21kA6uWA0yrESHiFSpQYnyF3JPuU6IXXovkxRl6gWB51B2rvQIipP0YwOLnB1o6c6dQFLuUnnOZepgHWgdm+B4E3tcoyx+RxBF4DGPTfpdjqZTCAT0tyKS6+hxNc1+UF/kYafZ1iQ==
  template:
    metadata:
      name: stripe-secrets
      namespace: oms
    type: Opaque
