apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: oms
spec:
  ports:
  - port: 27017
  selector:
    app: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: oms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:7
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: oms
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: oms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        env:
        - name: POSTGRES_DB
          value: stock
        - name: POSTGRES_USER
          value: stock
        - name: POSTGRES_PASSWORD
          value: stock123
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true
      volumes:
      - name: init-script
        configMap:
          name: postgres-init-script
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: oms
spec:
  ports:
  - port: 5672
    name: amqp
  - port: 15672
    name: management
  selector:
    app: rabbitmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: oms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672
        - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: oms
spec:
  ports:
  - port: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: oms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
# CONSUL DISABLED - Using Kubernetes DNS instead
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: consul
#   namespace: oms
# spec:
#   ports:
#   - port: 8500
#   selector:
#     app: consul
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: consul
#   namespace: oms
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: consul
#   template:
#     metadata:
#       labels:
#         app: consul
#     spec:
#       containers:
#       - name: consul
#         image: hashicorp/consul:latest
#         args:
#         - agent
#         - -server
#         - -ui
#         - -bootstrap-expect=1
#         - -client=0.0.0.0
#         ports:
#         - containerPort: 8500
