apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments
  namespace: oms
  labels:
    app: payments
    component: backend-service
    app.kubernetes.io/name: payments
    app.kubernetes.io/part-of: oms
automountServiceAccountToken: true
