apiVersion: v1
kind: ServiceAccount
metadata:
  name: kitchen-display
  namespace: oms
  labels:
    app: kitchen-display
    component: frontend
    app.kubernetes.io/name: kitchen-display
    app.kubernetes.io/part-of: oms
automountServiceAccountToken: false  # Frontend doesn't need K8s API access
