# Optional Development Tools
# Based on docker-compose-prod.yml
# These are NOT required for production

---
# Mongo Express - MongoDB Web UI
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: oms
spec:
  ports:
  - port: 8081
    name: http
    protocol: TCP
  selector:
    app: mongo-express

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: oms
  labels:
    app: mongo-express
    component: dev-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
        component: dev-tools
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:latest
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: "mongodb"
        - name: ME_CONFIG_BASICAUTH
          value: "false"
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"

---
# PgAdmin - PostgreSQL Web UI
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: oms
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
  selector:
    app: pgadmin

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: oms
  labels:
    app: pgadmin
    component: dev-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
        component: dev-tools
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:latest
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "admin@stock.com"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "admin123"
        - name: PGADMIN_CONFIG_SERVER_MODE
          value: "False"
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"

---
# Stripe CLI - For local webhook testing
# Note: Requires STRIPE_API_KEY environment variable
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stripe-cli
  namespace: oms
  labels:
    app: stripe-cli
    component: dev-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stripe-cli
  template:
    metadata:
      labels:
        app: stripe-cli
        component: dev-tools
    spec:
      containers:
      - name: stripe-cli
        image: stripe/stripe-cli:latest
        command:
        - stripe
        - listen
        - --forward-to
        - http://payments.oms.svc.cluster.local:8082/webhook
        - --skip-verify
        env:
        - name: STRIPE_API_KEY
          valueFrom:
            secretKeyRef:
              name: stripe-secrets
              key: STRIPE_SECRET_KEY
        - name: STRIPE_DEVICE_NAME
          value: "k8s-stripe-cli-local"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
