apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Configuration management for production environment

resources:
- orders-mongodb-secret.yaml

patches:
- path: configmap-patch.yaml
  target:
    kind: ConfigMap
    name: oms-config
