apiVersion: v1
kind: ServiceAccount
metadata:
  name: orders
  namespace: oms
  labels:
    app: orders
    component: backend-service
    app.kubernetes.io/name: orders
    app.kubernetes.io/part-of: oms
automountServiceAccountToken: true
