apiVersion: v1
kind: ConfigMap
metadata:
  name: oms-config
  namespace: oms
  labels:
    app.kubernetes.io/name: oms-config
    app.kubernetes.io/part-of: oms
    app.kubernetes.io/managed-by: kustomize
data:
  MONGO_URI: "mongodb://mongodb.oms.svc.cluster.local:27017/orders"
  POSTGRES_HOST: "postgres.oms.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "stock"
  POSTGRES_DB: "stock"
  AMQP_USER: "guest"
  AMQP_PASS: "guest"
  AMQP_HOST: "rabbitmq.oms.svc.cluster.local"
  AMQP_PORT: "5672"
  RABBITMQ_USER: "guest"
  RABBITMQ_HOST: "rabbitmq.oms.svc.cluster.local"
  RABBITMQ_PORT: "5672"
  RABBITMQ_PASS: "guest"
  REDIS_ADDR: "redis.oms.svc.cluster.local:6379"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq.oms.svc.cluster.local:5672/"
  POSTGRES_URI: "postgresql://stock:stock123@postgres.oms.svc.cluster.local:5432/stock?sslmode=disable"
  OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector-collector.opentelemetry.svc.cluster.local:4317"
  ORDERS_GRPC_ADDR: "orders.oms.svc.cluster.local:9000"
  STOCK_GRPC_ADDR: "stock.oms.svc.cluster.local:9003"
  CONSUL_ADDR: "consul.oms.svc.cluster.local:8500"
