apiVersion: v1
kind: ServiceAccount
metadata:
  name: kitchen
  namespace: oms
  labels:
    app: kitchen
    component: consumer-service
    app.kubernetes.io/name: kitchen
    app.kubernetes.io/part-of: oms
automountServiceAccountToken: true
